// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aaozkcjfxchwojpkzxsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhb3prY2pmeGNod29qcGt6eHNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NDI1MjEsImV4cCI6MjA2ODMxODUyMX0.58fM4b9soA3bWx0Z2ZsXmdCM9_h2uKwddIpTUqnJgj0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});